# REQUIRES THE REST CLIENT EXTENSION
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client

@baseUrl=http://localhost:7071/api
@patientKey=2a3acc9e-13de-4fef-8af2-0fb2c70e03ff

### GetPatients:- get all patients.
GET {{baseUrl}}/patients

###GetPatient:
GET  {{baseUrl}}/patients/{{patientKey}}

### Create Patient
POST {{baseUrl}}/patients
Content-Type: application/json

{
    "PatientKey": "2A3ACC9E-13DE-4FEF-8AF2-0FB2C70E03EF",
    "FirstName": "Shahrukh",
    "LastName": "Khan",
    "DateOfBirth": "13-05-1998",
    "Gender": "Male",
    "StreetAddress": "76 Collins Road",
    "Suburb": "Richmond",
    "Postcode": "3000",
    "HealthCoverType": "Bupa",
    "PolicyNumber": "123456",
	"RecaptchaResponse": "abcd1234"
}